// Copyright (c) ZeniMax Media Inc.
// Licensed under the GNU General Public License 2.0.
// Ported from rogue/m_turret.h (frame indices; "This file generated by
// qdata - Do NOT Modify" in the original).

export const FRAME_stand01 = 0;
export const FRAME_stand02 = 1;
export const FRAME_active01 = 2;
export const FRAME_active02 = 3;
export const FRAME_active03 = 4;
export const FRAME_active04 = 5;
export const FRAME_active05 = 6;
export const FRAME_active06 = 7;
export const FRAME_run01 = 8;
export const FRAME_run02 = 9;
export const FRAME_pow01 = 10;
export const FRAME_pow02 = 11;
export const FRAME_pow03 = 12;
export const FRAME_pow04 = 13;
export const FRAME_death01 = 14;
export const FRAME_death02 = 15;

export const MODEL_SCALE = 3.5;
