// snd_loc.h -- private sound functions and the sound mixer's shared state.
//
// SNDDMA_Init/SNDDMA_GetDMAPos/SNDDMA_Shutdown/SNDDMA_BeginPainting/
// SNDDMA_Submit ("SYSTEM SPECIFIC FUNCTIONS" in the header) are confirmed by
// grep to be defined only in platform sound backends (null/snddma_null.c,
// linux/snd_linux.c, win32/snd_win.c, irix/snd_irix.c) -- never in
// client/snd_dma.c itself, which only calls through them. Per PORTING.md's
// platform mapping these five belong to a future src/platform/snd.ts, not
// to any src/client/*.c stub in this unit's scope.
//
// The remaining functions (GetWavinfo, S_InitScaletable, S_LoadSound,
// S_IssuePlaysound, S_PaintChannels, S_PickChannel, S_Spatialize) are ported
// as functions in the snd_dma.ts/snd_mem.ts/snd_mix.ts pending stubs per
// their real defining file (confirmed by grep, not by the header's file
// grouping).

import { type Vec3, vec3 } from "../shared/math";
import { MAX_QPATH, type CvarT } from "../shared/q_shared";

// !!! if this is changed, the asm code must change !!!
export class PortableSamplepairT {
  left = 0;
  right = 0;
}

export class SfxcacheT {
  length = 0;
  loopstart = 0;
  speed = 0; // not needed, because converted on load?
  width = 0;
  stereo = 0;
  data: Uint8Array = new Uint8Array(0); // variable sized in C (`byte data[1]`)
}

export class SfxT {
  name = ""; // MAX_QPATH
  registration_sequence = 0;
  cache: SfxcacheT | null = null;
  truename: string | null = null;
}

// a playsound_t will be generated by each call to S_StartSound, when the
// mixer reaches playsound->begin, the playsound will be assigned to a
// channel
export class PlaysoundT {
  prev: PlaysoundT | null = null;
  next: PlaysoundT | null = null;
  sfx: SfxT | null = null;
  volume = 0;
  attenuation = 0;
  entnum = 0;
  entchannel = 0;
  fixed_origin = false; // use origin field instead of entnum's origin
  origin: Vec3 = vec3();
  begin = 0; // unsigned -- begin on this sample
}

export class DmaT {
  channels = 0;
  samples = 0; // mono samples in buffer
  submission_chunk = 0; // don't mix less than this #
  samplepos = 0; // in mono samples
  samplebits = 0;
  speed = 0;
  buffer: Uint8Array = new Uint8Array(0);
}

// !!! if this is changed, the asm code must change !!!
export class ChannelT {
  sfx: SfxT | null = null; // sfx number
  leftvol = 0; // 0-255 volume
  rightvol = 0; // 0-255 volume
  end = 0; // end time in global paintsamples
  pos = 0; // sample position in sfx
  looping = 0; // where to loop, -1 = no looping OBSOLETE?
  entnum = 0; // to allow overriding a specific sound
  entchannel = 0;
  origin: Vec3 = vec3(); // only use if fixed_origin is set
  dist_mult = 0; // distance multiplier (attenuation/clipK)
  master_vol = 0; // 0-255 master volume
  fixed_origin = false; // use origin instead of fetching entnum's origin
  autosound = false; // from an entity->sound, cleared each frame
}

export class WavinfoT {
  rate = 0;
  width = 0;
  channels = 0;
  loopstart = 0;
  samples = 0;
  dataofs = 0; // chunk starts this many bytes from file start
}

export const MAX_CHANNELS = 32;
export const channels: ChannelT[] = Array.from({ length: MAX_CHANNELS }, () => new ChannelT());

export let paintedtime = 0;
export let s_rawend = 0;

export function setPaintedtime(v: number): void {
  paintedtime = v;
}
export function setSRawend(v: number): void {
  s_rawend = v;
}

export const listener_origin: Vec3 = vec3();
export const listener_forward: Vec3 = vec3();
export const listener_right: Vec3 = vec3();
export const listener_up: Vec3 = vec3();

export const dma: DmaT = new DmaT();

// sentinel head node for the pending-playsound linked list (S_IssuePlaysound
// links real nodes in via ->prev/->next; this node is never itself played).
export const s_pendingplays: PlaysoundT = new PlaysoundT();

export const MAX_RAW_SAMPLES = 8192;
export const s_rawsamples: PortableSamplepairT[] = Array.from({ length: MAX_RAW_SAMPLES }, () => new PortableSamplepairT());

// s_volume/s_nosound/s_loadas8bit/s_khz/s_show/s_mixahead/s_testsound/
// s_primary are cvars registered by S_Init (snd_dma.c); grouped into one
// mutable holder (mirrors server.ts's svClientHolder/sv_game.ts's geHolder
// pattern) rather than N individual setter functions, since there are eight
// of them and none is read outside the sound module -- reported deviation
// from server.ts's per-cvar setter style.
export const sndCvars: {
  s_volume: CvarT | null;
  s_nosound: CvarT | null;
  s_loadas8bit: CvarT | null;
  s_khz: CvarT | null;
  s_show: CvarT | null;
  s_mixahead: CvarT | null;
  s_testsound: CvarT | null;
  s_primary: CvarT | null;
} = {
  s_volume: null,
  s_nosound: null,
  s_loadas8bit: null,
  s_khz: null,
  s_show: null,
  s_mixahead: null,
  s_testsound: null,
  s_primary: null,
};

// MAX_QPATH import kept for SfxT.name's size-limit documentation.
export const SFX_NAME_MAX_LEN = MAX_QPATH;
